name: Autorespond
on:
  issues:
    types: [opened, edited]
jobs:
  issue_response:
    runs-on: ubuntu-latest
    name: Issue Response
    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: '![THE ROOK!!!!](https://media.tenor.com/_NhXToxqMsAAAAAC/the-rook-gothamchess.gif)'
